// <auto-generated />
using IT3047CGroupProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3047CGroupProject.Migrations
{
    [DbContext(typeof(PhotographyContext))]
    [Migration("20251102194856_Locations")]
    partial class Locations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3047CGroupProject.Models.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<string>("CameraBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CameraPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            CameraId = 1,
                            CameraBrand = "Canon",
                            CameraDescription = "A high-resolution full-frame mirrorless camera with advanced features.",
                            CameraModel = "EOS R5",
                            CameraName = "Canon EOS R5",
                            CameraPrice = 3899.00m
                        },
                        new
                        {
                            CameraId = 2,
                            CameraBrand = "Nikon",
                            CameraDescription = "A versatile full-frame mirrorless camera with excellent image quality.",
                            CameraModel = "Z7 II",
                            CameraName = "Nikon Z7 II",
                            CameraPrice = 2999.95m
                        },
                        new
                        {
                            CameraId = 3,
                            CameraBrand = "Sony",
                            CameraDescription = "A popular full-frame mirrorless camera known for its speed and performance.",
                            CameraModel = "Alpha a7 III",
                            CameraName = "Sony Alpha a7 III",
                            CameraPrice = 1998.00m
                        });
                });

            modelBuilder.Entity("IT3047CGroupProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Landscape"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Portrait"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Wildlife"
                        });
                });

            modelBuilder.Entity("IT3047CGroupProject.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            CategoryId = 1,
                            LocationDescription = "A stunning location known for its waterfalls and granite cliffs.",
                            LocationName = "Yosemite National Park"
                        },
                        new
                        {
                            LocationId = 2,
                            CategoryId = 2,
                            LocationDescription = "A popular urban park perfect for portrait photography.",
                            LocationName = "Central Park"
                        },
                        new
                        {
                            LocationId = 3,
                            CategoryId = 3,
                            LocationDescription = "A prime location for capturing wildlife in their natural habitat.",
                            LocationName = "Serengeti National Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
